#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
exec chpst -u "$USER":"$GROUP" unoconv --listener --server=0.0.0.0 --port=2002
